# Generated by Django 4.1.7 on 2023-03-21 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesssystem', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='contactus',
            fields=[
                ('firstname', models.TextField(max_length=255)),
                ('lastname', models.TextField(max_length=255)),
                ('email', models.TextField(primary_key=True, serialize=False)),
                ('comment', models.TextField(max_length=255)),
            ],
            options={
                'db_table': 'contactus',
            },
        ),
    ]
