# Generated by Django 4.1.7 on 2023-03-23 16:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesssystem', '0002_contactus'),
    ]

    operations = [
        migrations.CreateModel(
            name='register',
            fields=[
                ('username', models.TextField(max_length=100)),
                ('password', models.TextField(max_length=100)),
                ('email', models.EmailField(max_length=254, primary_key=True, serialize=False)),
                ('phonenumber', models.TextField(max_length=11)),
            ],
            options={
                'db_table': 'register',
            },
        ),
        migrations.AlterField(
            model_name='contactus',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
